version: '3.8'  # Версия Compose

services:
  web:  # Имя сервиса
    build:
      context: .  # Указывает, что Dockerfile находится в текущей директории
      dockerfile: Dockerfile  # Имя Dockerfile (опционально, если имя - Dockerfile)
    ports:
      - "8080:8080"  # Пробрасывает порт 8080 контейнера на 8080 хоста
    volumes:
      - .:/web  # Связывает локальную директорию с контейнером для разработки
      - /web/node_modules  # Исключает node_modules из монтирования (опционально)
    environment:
      NODE_ENV: production  # Устанавливает переменные окружения
    command: ["npm", "run", "serve"]  # Переопределяет команду запуска (можно не указывать, если в Dockerfile уже есть CMD)

# Дополнительные настройки
# - context: можно поменять на другой путь, если Dockerfile в поддиректории
# - volumes: полезны для разработки, чтобы не пересобирать контейнер при изменении кода
