version: '3.8' 

services:
  web:  
    build:
      context: .  
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    volumes:
      - .:/web  
      - /web/node_modules 
    environment:
      NODE_ENV: production 
    command: ["npm", "run", "serve"]  